name: app_template
description: A generic Flutter app template for quick project setup
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3

  # Routing
  go_router: ^17.0.0

  # Firebase Services
  firebase_app_check: ^0.4.0+1
  firebase_core: ^4.2.1
  firebase_remote_config: ^6.1.2

  # Package dependencies
  core:
    path: ../packages/core
  feature:
    path: ../packages/feature

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/images/

